---
title: "Hierarchical Regression"
author: "Ernestine Brannon"
output: html_document 
---
```{r}
library(knitr)
library(tidyverse)
library(rstatix)
library(gridExtra)
library(rempsyc)
library(psych)
library(ggstatsplot)
library(papaja)
pkgs <- c("effectsize", "flextable", "broom", "report")
install_if_not_installed(pkgs)
library(effectsize)
library(flextable)
library(broom)
library(report)
library(doBy)
library(RColorBrewer)
library(ggpubr)
library(ggsignif)
library(GGally)
```



```{r}
all_task<- cbind(s2r_abs,s2v_abs) %>% 
  select(sid, frame_effect_r, frame_effect_v, frame_size)
p_df<- perception_abs %>% 
  select(magnitude, sid) %>% 
  rename(sub_1 =sid)
all_task<- cbind(all_task,p_df)

all_task<- all_task %>% 
  select(-sub_1)
```

```{r model comparison frame 175}

df_175<- all_task %>% 
  filter(frame_size == 175)

df_175_across<- df_175 %>% 
  select(-sid, -frame_size)

#ggpairs(df_175_across)


model_1_175<- lm(magnitude~frame_effect_v, df_175)

model_2_175<- lm(magnitude~ frame_effect_v +frame_effect_r, df_175)

aov_175<- anova(model_1_175,model_2_175)
summary(aov_175)
```
```{r model comparison frame 410}

df_410<- all_task %>% 
  filter(frame_size == 410)

df_410_across<- df_410 %>% 
  select(-sid, -frame_size)

#ggpairs(df_410_across)


model_1_410<- lm(magnitude~frame_effect_v, df_410)

model_2_410<- lm(magnitude~ frame_effect_v +frame_effect_r, df_410)

aov_410<- anova(model_1_410,model_2_410)
summary(aov_410)
```

```{r model comparison frame 645}

df_645<- all_task %>% 
  filter(frame_size == 645)

df_645_across<- df_645 %>% 
  select(-sid, -frame_size)

#ggpairs(df_410_across)


model_1_645<- lm(magnitude~frame_effect_v, df_645)

model_2_645<- lm(magnitude~ frame_effect_v +frame_effect_r, df_645)

aov_645<- anova(model_1_410,model_2_410)
summary(aov_645)
```

```{r model comparison frame 880}

df_880<- all_task %>% 
  filter(frame_size == 880)

df_880_across<- df_880 %>% 
  select(-sid, -frame_size)

#ggpairs(df_880_across)

model_1_880<- lm(magnitude~frame_effect_v, df_880)

model_2_880<- lm(magnitude~ frame_effect_v +frame_effect_r, df_880)

aov_880<- anova(model_1_880,model_2_880)
summary(aov_880)

```






