---
title: "Saccade-to-Rod Data Processing"
author: "Ernestine Brannon"
output: html_document 
---

```{r setup, include = FALSE, echo= FALSE}

#rm(list=ls())

library(tidyverse)
library(rstatix)
library(gridExtra)
library(rempsyc)
library(psych)

pkgs <- c("effectsize", "flextable", "broom", "report")
install_if_not_installed(pkgs)
library(effectsize)
library(flextable)
library(broom)
library(report)
library(doBy)

source("./Utilities/PsyFUN_source.R")

f_x <- 960 #fixation point x value

f_y <-  850 # fixation point y value
```

```{r load vertical data as v_data, include=FALSE, echo=FALSE}
#Load vertical data
data_dir_v <-"./data/v_results"


sids_v<- list.files(data_dir_v) #subject IDS

v_data_raw<- NULL #empty variable that will be filled through the for loop below

#Bind together all the data across subjects
for (i in seq_along(sids_v)) {
  
  fname <- list.files(file.path(data_dir_v, sids_v[i]), 
                      pattern = "RESULTS_FILE")#, full.names = TRUE)
  
  v_tmp_data <- rio::import(paste0(data_dir_v,"/", sids_v[i]), na.strings = c("NULL"))
  
  v_tmp_data$sid <- sids_v[i]
  
  v_data_raw <- rbind(v_data_raw, v_tmp_data) #has all of data across subjects
  
}

v_data<-v_data_raw %>% 
  filter(TRIAL_OUTCOME=="good")
```

```{r}
#Add columns saccade error x and y as sacc_v_error_y and sacc_y_error_x
v_data_calc<- v_data %>%
  mutate(
    sacc_v_error_y = f_y - EYE_Y, #fixationY-saccadeY
    sacc_v_error_x = EYE_X - f_x, #saccadeX-fix
    v_error_radians = atan2(sacc_v_error_x,sacc_v_error_y), #returns angle in radians for tangent y/x,
    v_error = v_error_radians *(180/pi)   #multiply by 180 then divide by pi to get degrees
    
  )
```

```{r v magnitude for each frame size/tilt ,include=FALSE,echo=FALSE}
#The effect of the frames was quantified by subtracting the mean errors for the counterclockwise-tilted frames from those of the clockwise-tilted frames then halving this value to get a measure of the average effect of a single frame (negative values indicated eye movements that deviated in the direction opposite the tilt of the frame).

saccade_to_vert_magnitude<-v_data_calc %>% 
  group_by(sid,FRAME_SIZE_VAL, FRAME_TILT_VAL) %>% 
  summarize(m_errors = mean(v_error)) %>% #The magnitude of the errors were averaged across trials for each of frame tilt/ size and  averaged across rod tilts 
  mutate(FRAME_TILT_VAL=recode(FRAME_TILT_VAL, '-15'='ccw', '15'='cw')) %>% 
  select(sid, FRAME_SIZE_VAL,FRAME_TILT_VAL, m_errors) %>% 
  ungroup() %>% 
  group_by(FRAME_SIZE_VAL,FRAME_TILT_VAL) %>% 
  pivot_wider(names_from = FRAME_TILT_VAL, values_from = m_errors) %>% 
  mutate(frame_effect_v= (cw-ccw)/2)

saccade_to_vert_magnitude$FRAME_SIZE_VAL<-as.factor(saccade_to_vert_magnitude$FRAME_SIZE_VAL)

```

```{r}
s2v_ttest_df<-saccade_to_vert_magnitude %>% group_by(FRAME_SIZE_VAL) %>% do(tidy(t.test(.$frame_effect_v)))
nice_table(s2v_ttest_df)
```

```{r}
set.seed(1)
saccade_to_vert_magnitude<- saccade_to_vert_magnitude %>% 
  ungroup()
ggwithinstats(
  data = saccade_to_vert_magnitude,
  x = FRAME_SIZE_VAL,
  y = frame_effect_v,
  type = "parametric"
)
```

